apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nodedev
  name: nodedev
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nodedev
  strategy: {}
  template:
    metadata:
      labels:
        run: nodedev
    spec:
      containers:
      - image: nodedev:latest
        name: nodedev
        imagePullPolicy: IfNotPresent
        command: ["npm"]
        args: ["run", "dev"]
        ports:
        - containerPort: 8080
        - containerPort: 5858
        resources: {}
        volumeMounts:
          - mountPath: /app/app
            name: mount
      volumes:
      - name: mount
        hostPath:
          path: /mounted-nodedev/app
