apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nodedev
  name: nodedev
spec:
  ports:
  - name: server
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: debug
    port: 5858
    protocol: TCP
    targetPort: 5858
  selector:
    run: nodedev
  type: LoadBalancer
status:
  loadBalancer: {}
